In [1]:
import numpy as np

In [149]:
num_gates = 100
num_qubits = 4
num_gate_types = 5

pick = np.random.randint(low=0,high=num_qubits*num_gate_types, size=num_gates)

tensor = np.zeros((num_gates, num_qubits, num_gate_types))
for i,_ in enumerate(tensor):
    tensor[i, pick[i]//num_gate_types, pick[i]%num_gate_types] = 1

# print(pick)
# print(tensor)

In [99]:
global history
history = []

In [102]:
def func(x):
    u = x.reshape(x.shape[0],-1)
    t = u.T @ u
    val = np.trace(t) - np.log(np.linalg.det(t))
    
    history.append((x,val))
    return val

In [152]:
def get_one_hot(x):
    gate_choice = x.reshape((x.shape[0], -1)).argmax(axis=1)
    u = np.zeros((x.shape[0], x.shape[1]*x.shape[2]))
    u[np.arange(x.shape[0]), gate_choice] = 1
    u = u.reshape(x.shape)
    
    return u

In [175]:
def remove_id_gate(x):
    
    id_gate_column = x[:,:,0] # shape (num_gates, num_qubits)
     
    idx = np.argwhere(np.all(id_gate_column == 0,  axis=1)) # idx of non-identity gates
    
    u = np.zeros_like(x)
    
    u[:len(idx), ...] = x[idx.ravel()] # gather non-identity gates, pad the remaining positions with zeros
    
    #idx = np.argwhere(np.any(id_gate_column == 1,  axis=1))
    #x = np.delete(x, idx, axis=0)
    
    print(idx)
    
    return u

In [150]:
tensor = np.random.rand(num_gates, num_qubits, num_gate_types)
func(tensor)

637.7178653392845

In [177]:
a = get_one_hot(tensor)
print(a[:5])
b = remove_id_gate(a)
print(b)
print(b.shape)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]]
[[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [17]
 [18]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [41]
 [42]
 [43]
 [45]
 [46]
 [47]
 [48]
 [49]
 [50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]
 [58]
 [59]
 [60]
 [61]
 [62]
 [63]
 [65]
 [66]
 [67]
 [68]
 [69]
 [71]
 [72]
 [73]
 [74]
 [75]
 [76]
 [78]
 [79]
 [80]
 [81]
 [82]
 [83]
 [84]
 [86]
 [87]
 [89]
 [90]
 [91]
 [92]
 [93]
 [95]
 [96]
 [97]
 [99]]
[[[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  