In [20]:
import numpy as np
from qiskit.opflow import I,X,Y,Z

In [10]:
perp = np.random.permutation(5)
perp

array([2, 3, 4, 0, 1])

In [8]:
a = np.array([1,10,100,1000,10000])

In [12]:
a[perp]

array([  100,  1000, 10000,     1,    10])

In [15]:
tf = (a == 1)

In [18]:
a[a == 1] *= -1

In [19]:
a

array([   -1,    10,   100,  1000, 10000])

In [21]:
Z^(I^(1-1))

PauliOp(Pauli('Z'), coeff=1.0)