In [4]:
import numpy as np
import time

In [96]:
num_samples = 100000
fidelities = np.random.uniform(0,1,(10000,num_samples))
k = 10

In [97]:
save_a = np.zeros(1000)
save_b = np.zeros(1000)
save_c = np.zeros(1000)

In [98]:
start_time = time.time()
a = np.sort(fidelities)
save_a = a[:,k]
print("--- %s seconds ---" % (time.time() - start_time))

--- 155.47774195671082 seconds ---


In [99]:
start_time = time.time()
b = np.partition(fidelities,k)[:,:k+1]
save_b = np.sort(b)[:,-1]
print("--- %s seconds ---" % (time.time() - start_time))

--- 149.42562294006348 seconds ---


In [100]:
start_time = time.time()
for i in range(10000):
    temp = np.partition(fidelities[i],k)[:k+1]
    save_c[i] = np.sort(temp)[-1]
print("--- %s seconds ---" % (time.time() - start_time))

IndexError: index 1000 is out of bounds for axis 0 with size 1000

In [89]:
save_a[:5]

array([0.0001011 , 0.00011269, 0.00018293, 0.00016437, 0.00013356])

In [90]:
save_b[:5]

array([0.0001011 , 0.00011269, 0.00018293, 0.00016437, 0.00013356])

In [91]:
save_c[:5]

array([0.0001011 , 0.00011269, 0.00018293, 0.00016437, 0.00013356])

In [95]:
save_c.shape

(1000,)

In [59]:
sum(save_a == save_b)

/Users/trongduong/opt/anaconda3/envs/QML/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


TypeError: 'bool' object is not iterable

In [19]:
b = np.array([2,4,5,3,1])
np.partition(b,1)

array([1, 2, 5, 3, 4])

In [1]:
dict_1 = {'x[0]':1, 'x[1]':2}
dict_2 = {'t[0]':3, 't[1]':4}

In [4]:
{**dict_1, **dict_2}

{'x[0]': 1, 'x[1]': 2, 't[0]': 3, 't[1]': 4}