In [22]:
from qiskit.opflow import X, I, Y,Z
import qiskit
from typing import Union
op = (X ^ I) + (Y ^ 2)

In [2]:
type(op)

qiskit.opflow.primitive_ops.pauli_sum_op.PauliSumOp

In [10]:
(X ^ I).to_matrix()

array([[0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [6]:
op.to_matrix()

array([[ 0.+0.j,  0.+0.j,  1.+0.j, -1.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [-1.+0.j,  1.+0.j,  0.+0.j,  0.+0.j]])

In [14]:
type(X^I^X)

qiskit.opflow.primitive_ops.pauli_op.PauliOp

In [24]:
sum([I,X,Y,Z]).to_matrix()

array([[2.+0.j, 1.-1.j],
       [1.+1.j, 0.+0.j]])

In [16]:
isinstance(X^I^X, Union[qiskit.opflow.primitive_ops.pauli_sum_op.PauliSumOp, qiskit.opflow.primitive_ops.pauli_op.PauliOp])

TypeError: Subscripted generics cannot be used with class and instance checks

In [26]:
help(I)

Help on PauliOp in module qiskit.opflow.primitive_ops.pauli_op object:

class PauliOp(qiskit.opflow.primitive_ops.primitive_op.PrimitiveOp)
 |  PauliOp(*args, **kwargs)
 |  
 |  Class for Operators backed by Terra's ``Pauli`` module.
 |  
 |  Method resolution order:
 |      PauliOp
 |      qiskit.opflow.primitive_ops.primitive_op.PrimitiveOp
 |      qiskit.opflow.operator_base.OperatorBase
 |      abc.ABC
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, primitive: qiskit.quantum_info.operators.symplectic.pauli.Pauli, coeff: Union[complex, qiskit.circuit.parameterexpression.ParameterExpression] = 1.0) -> None
 |      Args:
 |          primitive: The Pauli which defines the behavior of the underlying function.
 |          coeff: A coefficient multiplying the primitive.
 |      
 |      Raises:
 |          TypeError: invalid parameters.
 |  
 |  __new__ lambda cls, *args, **kwargs
 |  
 |  __str__(self) -> str
 |      Return str(self).
 |  
 |  add(self, oth

In [32]:
import numpy as np

In [33]:
np.real((I^3).to_matrix())

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
a = np.zeros((3,3), dtype=np.complex_)
print(a)
print(type(a))

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
<class 'numpy.ndarray'>


In [36]:
np.real(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])