In [1]:
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.opflow import I,X,Y,Z
import numpy as np

In [2]:
qc = QuantumCircuit(2)
theta = ParameterVector('theta',4)

In [3]:
qc.rx(theta[0],0)
qc.cry(theta[1],1,0)
qc.rzz(theta[2],0,1)
qc.h(0)
qc.crx(theta[3],1,0)
qc.draw()

┌──────────────┐┌──────────────┐               ┌───┐┌──────────────┐
q_0: ┤ Rx(theta[0]) ├┤ Ry(theta[1]) ├─■─────────────┤ H ├┤ Rx(theta[3]) ├
     └──────────────┘└──────┬───────┘ │ZZ(theta[2]) └───┘└──────┬───────┘
q_1: ───────────────────────■─────────■─────────────────────────■────────

In [4]:
num_ops = sum(qc.count_ops().values())
print(num_ops)

5


In [5]:
len(qc.parameters)

4

In [6]:
from qiskit.circuit.library import QFT
from qiskit.quantum_info import Statevector
from qiskit.opflow.primitive_ops import CircuitOp, MatrixOp

In [7]:
qft_circ = QFT(num_qubits=4, approximation_degree=0, do_swaps=True, inverse=False, insert_barriers=False, name=None)

In [8]:
qft_circ.draw()

┌────────────┐
q_0: ┤0           ├
     │            │
q_1: ┤1           ├
     │  circuit-8 │
q_2: ┤2           ├
     │            │
q_3: ┤3           ├
     └────────────┘

In [9]:
init_state = Statevector.from_label('0110')
qft_state = init_state.evolve(qft_circ)
qft_projector = qft_state.to_operator()
qft_projector.data

array([[ 6.25000000e-02+0.j        , -4.41941738e-02-0.04419417j,
        -3.82702125e-18+0.0625j    ,  4.41941738e-02-0.04419417j,
        -6.25000000e-02-0.j        ,  4.41941738e-02+0.04419417j,
         3.82702125e-18-0.0625j    , -4.41941738e-02+0.04419417j,
         6.25000000e-02+0.j        , -4.41941738e-02-0.04419417j,
        -3.82702125e-18+0.0625j    ,  4.41941738e-02-0.04419417j,
        -6.25000000e-02-0.j        ,  4.41941738e-02+0.04419417j,
         3.82702125e-18-0.0625j    , -4.41941738e-02+0.04419417j],
       [-4.41941738e-02+0.04419417j,  6.25000000e-02+0.j        ,
        -4.41941738e-02-0.04419417j,  0.00000000e+00+0.0625j    ,
         4.41941738e-02-0.04419417j, -6.25000000e-02+0.j        ,
         4.41941738e-02+0.04419417j,  0.00000000e+00-0.0625j    ,
        -4.41941738e-02+0.04419417j,  6.25000000e-02+0.j        ,
        -4.41941738e-02-0.04419417j,  0.00000000e+00+0.0625j    ,
         4.41941738e-02-0.04419417j, -6.25000000e-02+0.j        ,
         

In [10]:
qc = QuantumCircuit(4)
circuit_op = CircuitOp(qft_circ)
circuit_op.to_matrix()

array([[ 2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ,
         2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ,
         2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ,
         2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ,
         2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ,
         2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ,
         2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ,
         2.50000000e-01+0.j        ,  2.50000000e-01+0.j        ],
       [ 2.50000000e-01+0.j        ,  2.30969883e-01+0.09567086j,
         1.76776695e-01+0.1767767j ,  9.56708581e-02+0.23096988j,
         1.53080850e-17+0.25j      , -9.56708581e-02+0.23096988j,
        -1.76776695e-01+0.1767767j , -2.30969883e-01+0.09567086j,
        -2.50000000e-01+0.j        , -2.30969883e-01-0.09567086j,
        -1.76776695e-01-0.1767767j , -9.56708581e-02-0.23096988j,
        -1.53080850e-17-0.25j      ,  9.56708581e-02-0.23096988j,
         

In [11]:
circuit_op.to_matrix() - qft_projector.data

array([[ 0.1875    +0.j        ,  0.29419417+0.04419417j,
         0.25      -0.0625j    ,  0.20580583+0.04419417j,
         0.3125    +0.j        ,  0.20580583-0.04419417j,
         0.25      +0.0625j    ,  0.29419417-0.04419417j,
         0.1875    +0.j        ,  0.29419417+0.04419417j,
         0.25      -0.0625j    ,  0.20580583+0.04419417j,
         0.3125    +0.j        ,  0.20580583-0.04419417j,
         0.25      +0.0625j    ,  0.29419417-0.04419417j],
       [ 0.29419417-0.04419417j,  0.16846988+0.09567086j,
         0.22097087+0.22097087j,  0.09567086+0.16846988j,
        -0.04419417+0.29419417j, -0.03317086+0.23096988j,
        -0.22097087+0.13258252j, -0.23096988+0.15817086j,
        -0.20580583-0.04419417j, -0.29346988-0.09567086j,
        -0.13258252-0.13258252j, -0.09567086-0.29346988j,
        -0.04419417-0.20580583j,  0.15817086-0.23096988j,
         0.13258252-0.22097087j,  0.23096988-0.03317086j],
       [ 0.25      +0.0625j    ,  0.22097087+0.13258252j,
        -0.0

In [12]:
print(qft_projector.data.shape)
print(circuit_op.to_matrix().shape)

(16, 16)
(16, 16)


In [13]:
print(type(circuit_op))
print(type(qft_projector))

<class 'qiskit.opflow.primitive_ops.circuit_op.CircuitOp'>
<class 'qiskit.quantum_info.operators.operator.Operator'>


In [15]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

In [16]:
mat = MatrixOp(qft_projector).to_matrix()

In [17]:
mat

array([[ 6.25000000e-02+0.j        , -4.41941738e-02-0.04419417j,
        -3.82702125e-18+0.0625j    ,  4.41941738e-02-0.04419417j,
        -6.25000000e-02-0.j        ,  4.41941738e-02+0.04419417j,
         3.82702125e-18-0.0625j    , -4.41941738e-02+0.04419417j,
         6.25000000e-02+0.j        , -4.41941738e-02-0.04419417j,
        -3.82702125e-18+0.0625j    ,  4.41941738e-02-0.04419417j,
        -6.25000000e-02-0.j        ,  4.41941738e-02+0.04419417j,
         3.82702125e-18-0.0625j    , -4.41941738e-02+0.04419417j],
       [-4.41941738e-02+0.04419417j,  6.25000000e-02+0.j        ,
        -4.41941738e-02-0.04419417j,  0.00000000e+00+0.0625j    ,
         4.41941738e-02-0.04419417j, -6.25000000e-02+0.j        ,
         4.41941738e-02+0.04419417j,  0.00000000e+00-0.0625j    ,
        -4.41941738e-02+0.04419417j,  6.25000000e-02+0.j        ,
        -4.41941738e-02-0.04419417j,  0.00000000e+00+0.0625j    ,
         4.41941738e-02-0.04419417j, -6.25000000e-02+0.j        ,
         

In [18]:
np.linalg.eigvals(mat)

array([ 4.74705635e-17-6.71855513e-18j,  1.00000000e+00+6.71855513e-18j,
       -9.59362637e-18-9.41215610e-18j,  9.36071953e-18-4.92029398e-18j,
       -3.62025988e-32+1.73430238e-32j, -4.37389254e-34-7.78663071e-34j,
        2.60506983e-34+2.38622195e-34j, -6.09436884e-35-1.09523766e-35j,
        4.38839645e-49-3.39577653e-49j,  2.12576757e-50+4.41763842e-51j,
       -4.95385932e-51-1.68111979e-51j, -1.72358801e-65+3.86980605e-65j,
       -7.89714931e-66+8.73591738e-66j, -9.72657432e-67+4.26252349e-67j,
        4.07971932e-81-2.52632517e-80j,  1.11399821e-81-4.08005169e-82j])